In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

data = load_iris()
X = data.data
y = data.target

# it is important to scale all data, as when using some sort of distance based model, for example k neighbours, one of the features might be way more senstive if it much greater than another feature. scaling equalized all features

scaler = StandardScaler()

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

x_train_scaled = scaler.fit_transform((x_train)) #when wanting to learn what scale to use, we add fit to the function.
x_test_scaled = scaler.transform((x_test)) # when wanting to just scale, we only use the transform method.
x_train_scaled


array([[ 7.35398679e-01,  2.98207551e-01,  4.68145647e-01,
         4.29647681e-01],
       [-8.57965125e-01,  7.39996516e-01, -1.22055608e+00,
        -1.26290379e+00],
       [-9.80531572e-01,  7.39996516e-01, -1.16426603e+00,
        -1.00251126e+00],
       [ 6.12832232e-01, -8.06264861e-01,  6.93305877e-01,
         8.20236482e-01],
       [-2.45132893e-01, -5.85370379e-01,  6.93305877e-01,
         1.08062902e+00],
       [-4.90265786e-01, -1.43581414e-01,  4.68145647e-01,
         4.29647681e-01],
       [ 1.22566446e-01, -1.43581414e-01,  8.05885993e-01,
         8.20236482e-01],
       [ 1.34823091e+00,  2.98207551e-01,  1.14362634e+00,
         1.47121782e+00],
       [ 1.71593025e+00, -1.43581414e-01,  1.19991640e+00,
         5.59843948e-01],
       [ 1.10309802e+00,  5.19102034e-01,  1.14362634e+00,
         1.73161035e+00],
       [ 2.45132893e-01, -1.91073727e+00,  7.49595935e-01,
         4.29647681e-01],
       [ 1.10309802e+00, -1.24805383e+00,  1.19991640e+00,
      

In [3]:
# CAN ALSO DO IT MANUALLY
import numpy as np
(x_train - np.mean(x_train, axis=0)) / np.std(x_train, axis=0)

array([[ 0.70920205,  0.3166047 ,  0.43577548,  0.41303791],
       [-0.51885344,  1.86281368, -1.15230002, -1.03314257],
       [ 0.46359095, -0.3460563 ,  0.32234152,  0.150096  ],
       [ 0.5863965 , -1.67137828,  0.3790585 ,  0.150096  ],
       [ 1.07761869,  0.0957177 ,  1.05966229,  1.59627649],
       [-1.50129784,  0.75837869, -1.32245097, -1.16461353],
       [ 1.69164644,  0.3166047 ,  1.28653022,  0.80745077],
       [ 2.30567418,  1.64192668,  1.68354909,  1.33333458],
       [-0.3960479 , -1.45049129,  0.0387566 , -0.1128459 ],
       [-1.13288119, -1.22960429,  0.43577548,  0.67597982],
       [-0.3960479 , -1.45049129, -0.01796038, -0.24431685],
       [ 0.83200759, -0.1251693 ,  1.17309625,  1.33333458],
       [-0.02763125, -0.78783029,  0.77607737,  0.93892172],
       [-0.1504368 , -1.22960429,  0.71936039,  1.07039268],
       [ 1.07761869,  0.0957177 ,  0.54920945,  0.41303791],
       [ 1.07761869, -0.1251693 ,  0.83279436,  1.46480554],
       [-1.37849229,  0.

In [6]:
#Min max scaling
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

x_train_scaled = scaler.fit_transform((x_train)) #when wanting to learn what scale to use, we add fit to the function.
x_test_scaled = scaler.transform((x_test))
x_train_scaled

array([[0.61764706, 0.5       , 0.61403509, 0.58333333],
       [0.32352941, 0.79166667, 0.12280702, 0.125     ],
       [0.55882353, 0.375     , 0.57894737, 0.5       ],
       [0.58823529, 0.125     , 0.59649123, 0.5       ],
       [0.70588235, 0.45833333, 0.80701754, 0.95833333],
       [0.08823529, 0.58333333, 0.07017544, 0.08333333],
       [0.85294118, 0.5       , 0.87719298, 0.70833333],
       [1.        , 0.75      , 1.        , 0.875     ],
       [0.35294118, 0.16666667, 0.49122807, 0.41666667],
       [0.17647059, 0.20833333, 0.61403509, 0.66666667],
       [0.35294118, 0.16666667, 0.47368421, 0.375     ],
       [0.64705882, 0.41666667, 0.84210526, 0.875     ],
       [0.44117647, 0.29166667, 0.71929825, 0.75      ],
       [0.41176471, 0.20833333, 0.70175439, 0.79166667],
       [0.70588235, 0.45833333, 0.64912281, 0.58333333],
       [0.70588235, 0.41666667, 0.73684211, 0.91666667],
       [0.11764706, 0.5       , 0.10526316, 0.04166667],
       [0.32352941, 0.58333333,

In [7]:
#manual min max
x_min = np.min(x_train, axis=0)
x_max = np.max(x_train, axis=0)
(x_train - x_min) / (x_max - x_min)

array([[0.61764706, 0.5       , 0.61403509, 0.58333333],
       [0.32352941, 0.79166667, 0.12280702, 0.125     ],
       [0.55882353, 0.375     , 0.57894737, 0.5       ],
       [0.58823529, 0.125     , 0.59649123, 0.5       ],
       [0.70588235, 0.45833333, 0.80701754, 0.95833333],
       [0.08823529, 0.58333333, 0.07017544, 0.08333333],
       [0.85294118, 0.5       , 0.87719298, 0.70833333],
       [1.        , 0.75      , 1.        , 0.875     ],
       [0.35294118, 0.16666667, 0.49122807, 0.41666667],
       [0.17647059, 0.20833333, 0.61403509, 0.66666667],
       [0.35294118, 0.16666667, 0.47368421, 0.375     ],
       [0.64705882, 0.41666667, 0.84210526, 0.875     ],
       [0.44117647, 0.29166667, 0.71929825, 0.75      ],
       [0.41176471, 0.20833333, 0.70175439, 0.79166667],
       [0.70588235, 0.45833333, 0.64912281, 0.58333333],
       [0.70588235, 0.41666667, 0.73684211, 0.91666667],
       [0.11764706, 0.5       , 0.10526316, 0.04166667],
       [0.32352941, 0.58333333,

# Summary
This chapter basically just covers how to scale the data so that it all is on the same scale. this is important for when we are using some sort of distance based algo, as greater values will have a much greater effect on the algo.