# Numpy intro


In [67]:
import numpy as np
print(np.__version__)


2.5.0


Python lists are slow and inneficient

In [68]:

my_list = [1,2,3,4]
my_list = my_list *2
print(my_list)



[1, 2, 3, 4, 1, 2, 3, 4]


Introducing.... numpy!

In [69]:
array = np.array([1,2,3,4])
print(array)

array *= 2
print(array)

[1 2 3 4]
[2 4 6 8]


# Multidimensional arrays

In [70]:
zerodimarray = np.array('A') #this is a zero dimensional array
print("zero dimensional array/ a single point.. basically no array: ", zerodimarray.ndim)

onedimarray = np.array(['A', 'B', 'C'])
print("one dimensional array, a single array: ", onedimarray.ndim)

twodimarray = np.array([['A', 'B', 'C'],
                        ['D', 'E', 'F'],
                        ['G', 'H', 'I']])
print("two dimensional array, array: ", twodimarray.ndim)


threedimarray = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                           [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                            [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', 'AZ']]])

print(threedimarray.shape)

#previous access - chain indexing:
print(threedimarray[0][0][0])

#multi dimensional indexing is faster than chain indexing
print(threedimarray[0,0,0])
print(threedimarray[0,0,1])
print(threedimarray[0,1,0])

#printing words
word = threedimarray[0,0,2] + threedimarray[0,0,0] + threedimarray[2,0,1]
print(word)

zero dimensional array/ a single point.. basically no array:  0
one dimensional array, a single array:  1
two dimensional array, array:  2
(3, 3, 3)
A
A
B
D
CAT


# Slicing

In [71]:
array = np.array( [ [1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12],
                    [13,14,15,16] ])
#array[start:end:step] slicing!
print("first row: ", array[0])
print("the first three rows: \n", array[0:3])
print("every second row: \n", array[0:4:2])


first row:  [1 2 3 4]
the first three rows: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
every second row: 
 [[ 1  2  3  4]
 [ 9 10 11 12]]


collumn selection:


In [72]:
print("collumn 1:", array[:, 0])
print("collumn 2:", array[:, 1])

print("first three collumns: \n", array[:, 0:3])

collumn 1: [ 1  5  9 13]
collumn 2: [ 2  6 10 14]
first three collumns: 
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


row and collumn selection

In [73]:
print("first two rows and first two collums: \n", array[0:2, 0:2])

print("first two rows last two collumns \n ", array[0:2, 2: ])

first two rows and first two collums: 
 [[1 2]
 [5 6]]
first two rows last two collumns 
  [[3 4]
 [7 8]]


# Arithmetic

In [74]:
#Scalar arithmetic

#every element gets the operation.
array = np.array([1,2,3])
print(array + 1 )
print(array - 2 )
print(array * 3 )
print(array / 4 )
print(array ** 5 )




[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [75]:

#vectorized math functions. actually just linear algebra

radii = np.array([1,2,3])
print(np.sqrt(array))

#given radii, make the area of each circl
print(radii ** 2 * np.pi)



[1.         1.41421356 1.73205081]
[ 3.14159265 12.56637061 28.27433388]


In [76]:
# Element wise arithmetic

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

# when adding two arrays, will do arithmetic on each element
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [77]:
# Comparison operators
# create boolean arrays, filter data, do element wise comparison

scores = np.array([91, 55, 100, 73, 82, 64])
print(scores == 100) # returns a boolean array
print(scores >= 60)
scores[scores < 60 ] = 0
print(scores)

[False False  True False False False]
[ True False  True  True  True  True]
[ 91   0 100  73  82  64]


# Broadcasting

Broadcasting allows numpy to perform operations on arrays with different shapes by virtually expanding dimensions so they match the larger arrays shape.
Broadcasting only works when: The dimensions have the same size OR one of the dims has size 1.


In [78]:
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [79]:
# multiplication table exercise

array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9], [10]])
print(array1.shape)
print(array2.shape)
print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


# Aggregate functions

summarize data and typical return a single value

In [88]:
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))

print(np.sum(array, axis=0)) #sums each collumn
print(np.sum(array, axis=1)) # sums each row


55
5.5
2.8722813232690143
8.25
1
10
0
[ 7  9 11 13 15]
[15 40]


# Filtering

refers to the process of selecting elements from a array that match a certain condition

In [97]:
ages = np.array( [[21,17,19,20,16,30,18,65],
                 [39, 22,15,99,18,19,20,21]])
teens = ages[ages < 18]
print(teens)
adults = ages[ (18 <= ages) & (ages <=  65)]
print(adults)
seniors = ages[ages >= 65]
print(seniors)
evens = ages[ages % 2 == 0]
print(evens)
odds = ages[ages % 2 != 0]
print(odds)

adults =  np.where(ages >= 18, ages, 0)
print(adults)

[17 16 15]
[21 19 20 30 18 65 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


# Random numbers

In [153]:
rng = np.random.default_rng(1)
print(rng.integers(low = 1, high = 101, size = (3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [162]:
np.random.seed(42)
print(np.random.uniform())
print(np.random.uniform(low = -1,high = 1, size = (3,2)))

0.3745401188473625
[[ 0.90142861  0.46398788]
 [ 0.19731697 -0.68796272]
 [-0.68801096 -0.88383278]]


In [169]:
array = np.array([1,2,3,4,5])
rng = np.random.default_rng()
rng.shuffle(array)
print(array)

fruits = np.array(['apple','banana','orange', 'coconut', 'pineapple'])
fruit = rng.choice(fruits, size = 3)
print(fruits)
print(fruit)


[4 3 2 5 1]
['apple' 'banana' 'orange' 'coconut' 'pineapple']
['apple' 'pineapple' 'apple']
